### ISSUE TITLE
Simple app to display a ABM example

### ISSUE THREAD

**Issue by f-lukas** [Pandora-IsoMemo/ABMS#1]
Subticket for https://github.com/Pandora-IsoMemo/drat/issues/40

**Comment by arunge** [comment]
See comment: https://github.com/Pandora-IsoMemo/deBInferS/issues/1#issuecomment-2326798149

**Comment by f-lukas** [comment]
A [main](https://pandoraapp.earth/app/abms) and [beta](https://pandoraapp.earth/app/abms-beta) version containing a minimal example is now deployed.
